"""
  Load Models from trained networks
  MIT License - C. Jarne V. 1.0 - 2025

This code loads, compiles, and iteratively analyzes recurrent neural
network models stored as .hdf5 files in a specified directory. For
each model, it retrieves connection weights, examines network properties,
and calculates eigenvalues and eigenvectors of the network's connection
matrix. The code also visualizes eigenvalue distributions
through plots saved in a "plots" directory.

---
### **1. Eigenvalue Analysis**
eigenvalues_[folder_name]_[i]_[mem_gap]_.png
  Full eigenvalue spectrum (complex plane) with unit circle and dominant eigenvalues highlighted.
sym_eigenvalues[folder_name]_[i]_[mem_gap]_.png
  Eigenvalues of the symmetric part of the recurrent weight matrix.

---

### **2. Connectivity Matrices**
[folder_name]_Connectivity_matrix_[i]_[f]_.png
  Visualizes input (`W_in`), recurrent (`W_rec`), and output (`W_out`) weight matrices.

---

### **3. Weight Distribution Analysis**
[folder_name]_WeightDistributionComparison_[i]_[f].png
  Compares weight distributions across layers (input, recurrent, output) against initialization schemes
  (Glorot Uniform/Orthogonal).

---

### **4. Advanced Spectral Analysis**
schur_decomp_network_[i].png
  Schur decomposition of the recurrent weight matrix (quasi-upper triangular form).
pseudospectrum_network_[i].png
  ε-pseudospectrum contours for stability analysis.
sym_antisym_network_[i].png
  Spectral properties of symmetric/antisymmetric components (eigenvalues and singular values).

---

### **5. Time-Series Activity**
[folder_name]_data_set_[weight_mask]_[mem_gap]_.png
  Sample input/output comparisons (ground truth vs. predictions).
- Neuronal activity plots
  Time-series activity of individual neurons (generated by `plot_sample`).

---

### **6. Numerical Data Files**
- [folder_name]_distance_sample.txt
  L2 distances between predicted and ground-truth outputs for samples.
- [folder_name]_freq_net.txt
  Dominant oscillatory frequencies derived from eigenvalues (Hz).
- [folder_name]_freq_net_units.txt
  Unit-specific oscillatory frequencies (if applicable).
- [folder_name]_H_number.txt
  Henrici’s departure from normality (measure of matrix non-normality).

---

### Filename Variables:
- `[folder_name]`: Name of the weights directory (e.g., `weights_N_100_0`)
- `[i]`: Model index (e.g., `0`, `1`, ...)
- `[f]`: Original `.hdf5` filename (e.g., `model_100_final.hdf5`)
- `[mem_gap]`: Memory delay parameter (task-dependent)
- `[weight_mask]`: Threshold for visualizing weak/strong weights (e.g., `0.001`)

"""

import os

# import warnings
os.environ['TF_DISABLE_GPU'] = '1'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import fnmatch
from matplotlib.colors import BoundaryNorm
from numpy import linalg as LA
from scipy.stats import norm
from scipy.linalg import schur
from utils.net_constraint_create import *
import tensorflow as tf
from tensorflow.keras.initializers import Initializer

# To plot network status
from plot_utilities.plot_neural_activity import *

#######################################################################################################
# Parameters:                                                                                         #
# task: "Simple DM", "Simple DM Long-short", "Simple DM 4 times","Simple DM 8 times", "Integral DM",  #
# "Integral DM signal keep", "Integral DM Cue"                                                        #
#######################################################################################################
task = "interval compare"
# "Simple DM 8 time encoded"#"Integral DM Cue"# "Integral DM signal keep"# "Simple DM"
# "Integral DM" #"Multi Ampli" #

# Pure Temporal tasks

if task in ["Simple DM", "Simple DM Long-short"]:
    # be aware of internal conf for data_set_generator to create one data set or the other
    from data_set_generators.generate_DM_delayed_response_sample import *

    mem_gap = 0
if task == "Simple DM 4 times":
    from data_set_generators.generate_DM_delayed_response_sample_mult_times_4 import *

    mem_gap = 0
if task == "Simple DM 8 times":
    from data_set_generators.generate_DM_delayed_response_sample_mult_times_8 import *

    mem_gap = 0
if task == "Simple DM 8 time encoded":
    from data_set_generators.generate_DM_delayed_response_sample_mult_times_8_intervals import *

    mem_gap = 0
# Integration tasks (temporal + integration +cue)

if task == "Integral DM":
    from data_set_generators.generate_perceptual_dm import *

    mem_gap = 200
if task == "Integral DM signal keep":
    from data_set_generators.generate_perceptual_dm_sig_not_end import *

    mem_gap = 50
if task == "Integral DM Cue":
    from data_set_generators.generate_perceptual_dm_sig_not_end_cue_mod import *

    mem_gap = 50
if task == "Multi Ampli":
    from data_set_generators.generate_DM_delayed_response_sample_mult_amplitude_8 import *

    mem_gap = 0

if task == "interval compare":
    from data_set_generators.generate_interval_comparison import *

    mem_gap = 20

lista_distancia_all = []
list_freq_sample_net = []
con_matrix_list = []
full_eigen_list = []
j2_full_eigen_list = []
H_number_list = []
net_freq = []
string_name_list = []
distance_list_all = []

current_directory = os.path.dirname(__file__)

# 01 DM simple (up/down)
# r_dir = current_directory + "/weights/01_DM_delayed_response/orthogonal_rrn_no_bias_term/weights_20_N_100_gap_4_/"

# 01 DM simple (up/down/short/long)
# r_dir = current_directory+"/weights/02_DM_delayed_response_long-short/orthogonal_rrn_no_bias_term/weights_20_N_100_gap_4/"

# DM 4 times
# r_dir = current_directory+"/weights/03_DM_delayed_response_4_times/orthogonal_rrn_no_bias_term/weights_20_N_100_gap_4/"

# DM 8 times
# r_dir = current_directory+"/weights/04_DM_delayed_response_8_times/orthogonal_rrn_no_bias_term/weights_20_N_100_gap_4/"

# Perceptual DM integral
# r_dir = current_directory+"/weights/05_Perceptual_dm_delayed_response/orthogonal_rrn_with_bias_term/weights_N_100_9/"
# r_dir = current_directory+"/weights/05_Perceptual_dm_delayed_response/large_out_weights/weights_N_100_4/"

# Integral DM signal keep
# r_dir=current_directory+"/weights/06_Perceptual_dm_delayed_response_signal_dont_end/orthogonal_rrn_no_bias_term/weights_N_100_9/"

# "Integral DM Cue"
# r_dir = current_directory+"/weights/07_Perceptual_dm_delayed_response_signal_dont_end_cue/orthogonal_rrn_no_bias_term/weights_N_100_4/"

# "Simple DM 8 time encoded"
# r_dir=current_directory+"/weights/08_DM_delayed_response_8_times_intervals/orthogonal_rrn_no_bias_term/weights_N_100_8/"
r_dir = current_directory + "/weights/10_interval_compare/weights_N_100_0/"
plot_dir = "plots"
sample_size = 10
N_rec = 100
# Rand normal inicialization with adjustable sigma
RandNor_sigma_adjuts = tf.keras.initializers.RandomNormal(mean=0.0, stddev=1.05 * np.sqrt(float(1) / float(N_rec)),
                                                          seed=None)


def custom_simple_rnn(**config):
    if 'time_major' in config:
        del config['time_major']  # Eliminar el argumento no reconocido
    return tf.keras.layers.SimpleRNN(**config)


class IdentityInitializer(Initializer):
    def __call__(self, shape, dtype=None):
        if shape[0] != shape[1]:
            raise ValueError("Identity matrix initializer requires a square matrix shape.")
        return np.identity(shape[0], dtype=dtype)


# Schur Decomposition and Visualization

def plot_schur_decomposition(W, plot_dir, filename):
    """Plot Schur decomposition of weight matrix"""
    T, _ = schur(W)  # Returns quasi-upper triangular matrix

    plt.figure(figsize=(8, 6))
    plt.imshow(np.abs(T), cmap='viridis', aspect='auto')
    plt.colorbar(label='Magnitude')
    plt.title('Schur Matrix (Upper Quasi-Triangular)')
    plt.savefig(f"{plot_dir}/schur_decomp_{filename}.png", dpi=150)
    plt.close()


# Pseudospectrum Visualization (Simplified)
def plot_pseudospectrum(W, plot_dir, filename, epsilons=[1e-3, 1e-2, 1e-1]):
    """Plot epsilon-pseudospectrum contours"""
    plt.figure(figsize=(8, 8))
    # True eigenvalues
    eigvals = LA.eigvals(W)
    plt.scatter(eigvals.real, eigvals.imag, c='k', s=10, alpha=0.8)

    # Grid for pseudospectrum
    real_grid = np.linspace(-2, 2, 100)
    imag_grid = np.linspace(-2, 2, 100)
    R, I = np.meshgrid(real_grid, imag_grid)
    Z = R + 1j * I

    # Compute resolvent norms
    for eps in epsilons:
        sv_min = np.zeros_like(Z)
        for i in range(Z.shape[0]):
            for j in range(Z.shape[1]):
                resolvent = LA.inv(Z[i, j] * np.eye(W.shape[0]) - W)
                sv_min[i, j] = 1 / LA.norm(resolvent, 2)
        plt.contour(R, I, sv_min, levels=[eps], colors=plt.cm.viridis(np.log10(eps) + 3))

    plt.title(r'$\epsilon$-Pseudospectrum Contours')
    plt.xlabel('Re($\lambda$)')
    plt.ylabel('Im($\lambda$)')
    plt.savefig(f"{plot_dir}/pseudospectrum_{filename}.png", dpi=150)
    plt.close()


def plot_sym_antisym_spectra(W, plot_dir, filename):
    """Plot spectral properties of symmetric/antisymmetric components"""
    W_sym = 0.5 * (W + W.T)
    W_antisym = 0.5 * (W - W.T)

    # Eigenvalues of symmetric part
    eig_sym = LA.eigvalsh(W_sym)  # Use eigh for symmetric matrices

    # Singular values of antisymmetric part
    svd_antisym = LA.svd(W_antisym, compute_uv=False)

    # Plotting
    fig, ax = plt.subplots(1, 2, figsize=(12, 5))

    ax[0].hist(eig_sym, bins=50, color='blue', alpha=0.7)
    ax[0].set_title('Symmetric Part Eigenvalues')
    ax[0].set_xlabel('Eigenvalue')

    ax[1].plot(svd_antisym, 'ro-', markersize=2)
    ax[1].set_title('Antisymmetric Part Singular Values')
    ax[1].set_yscale('log')

    plt.savefig(f"{plot_dir}/sym_antisym_{filename}.png", dpi=150)
    plt.close()


g = 1

# Generate the dataset:
# x_train, y_train, seq_dur = generate_trials(sample_size, mem_gap)
x_train, y_train, seq_dur, Ts = generate_trials(sample_size, mem_gap)
test = x_train[0:1, :, :]  # Here you select dataset which used for testing
test_set = x_train[0:20, :, :]
y_test_set = y_train[0:20, :, 0]

# Dataset to plot some results
sample_size_3 = 10
sample_size = 10

for root, sub, files in os.walk(r_dir):
    files = sorted(files)
    for i, f in enumerate(files):
        if fnmatch.fnmatch(f, '*100_final.hdf5'):
            folder_name = os.path.basename(root)
            r_dir = root
            string_name = str(folder_name)
            string_name_list.append(string_name)
            print(root)
            print(folder_name)
            print("file: ", f)
            print("string name: ", string_name)
            print("dir: ", r_dir)

            # Loading model

            custom_objects = {'NonNegLast': NonNegLast, 'NonNegLast_input': NonNegLast_input,
                              'my_init_exi_ini': my_init_exi_ini,
                              'my_init_rec': my_init_rec,
                              'SimpleRNN': custom_simple_rnn, 'IdentityInitializer': IdentityInitializer,
                              'RandNor_sigma_adjuts': RandNor_sigma_adjuts}

            model = tf.keras.models.load_model(r_dir + f, custom_objects=custom_objects, compile=False)

            # To get N_rec:
            for layer in model.layers:
                if 'rnn' in layer.name.lower():
                    weights = layer.get_weights()
                    N_rec = weights[0].shape[1]
                    print(f"N_rec: {N_rec}")
                    break

            # model = tf.keras.models.load_model(r_dir+"/"+f)
            # Compiling model for each file:
            model.compile(loss='mse', optimizer='Adam')
            print("-------------", i)

            # Network structure for debugging
            for jj, layer in enumerate(model.layers):
                # For debugging
                # print("Layer j: ", jj)
                # print(layer.get_config(), layer.get_weights())
                pass

            weights = model.layers[0].get_weights()
            weights__ = model.layers[0].get_weights()[0]
            weights_in = weights[0]
            weights_out = model.layers[1].get_weights()
            N_rec = len(weights_in[0])  # It has to match the value of the recorded trained network
            neurons = N_rec
            colors = plt.cm.rainbow(np.linspace(0, 1, neurons + 1))
            units = np.arange(len(weights))

            # RNN layer: auto select to load model with or without bias term
            for layer in model.layers:
                if 'rnn' in layer.name.lower():
                    weights = layer.get_weights()
                    if len(weights) > 2:  # [weights_in, weights_rec , bias] = 3 components
                        print("RNN Model has bias term")

                        weights_in = np.array(weights[0])
                        connection_used = np.array(weights[1])
                        connection = connection_used
                        biases = np.array(weights[2])

                        # arrays de NumPy -> set_weights
                        model.layers[0].set_weights([weights_in, connection_used, biases])
                        # to module/control weights
                        # model.layers[0].set_weights([1 * weights_in, 1 * connection_used, 1 * biases])

                    else:
                        print("RNN Model has not bias term")
                        weights = model.layers[0].get_weights()[1]
                        connection = weights
                        connection_used = connection
                        model.layers[0].set_weights([weights_in, connection_used])
                    break

            print("-------------\n-------------")

            con_matrix_list.append(weights)
            print("Array Length: ", np.arange(len(weights)))
            print("##########################\n ##########################")

            histo_lista = []
            array_red_list = []

            weight_mask = 0.001  # it could be for visualization/and or test stability or robustness
            weight_mask_2 = -0.001

            # Change "connection_used" for stability test
            # canceling connections that are weaker
            # than x% of the maximum or minimum

            # This is to study the symmetric matrix
            connection_sym = 0.5 * (connection + tf.transpose(connection))

            w, v = LA.eig(connection_used)

            print("Eigenvalues:\n", w)
            print("Eigenvectors:\n", v)
            print("Distance:", np.sqrt(w.real * w.real + w.imag * w.imag))

            list_distance = np.c_[w, w.real]
            list_distance_2 = np.c_[w, abs(w.real)]

            maximum = max(list_distance, key=lambda item: item[1])
            maximum_2 = max(list_distance_2, key=lambda item: item[1])
            eigen_main = maximum[0]
            eigen_main_2 = maximum_2[0]

            print("First Element", maximum)
            print("Maximum element", eigen_main)

            frequency = 0
            if eigen_main_2.imag == 0:
                frequency = 0
            else:
                frequency = abs(float(eigen_main_2.imag) / (3.14159 * float(eigen_main_2.real)))

            print("Dominant frequency for maximum eigenvalue position", frequency)

            list_moduls = np.sqrt(w.real * w.real + w.imag * w.imag)
            list_freq_ = 1000 * np.absolute(w.imag / (3.14159 * w.real))

            w_2 = list(w)

            list_dist_ordered = sorted(w_2, key=lambda x: abs(x.imag))
            print("Eigenvalue list Sorted", list_dist_ordered)

            j2 = [i for i in w_2 if abs(i.real * i.real + i.imag * i.imag) > 1 and i.imag != 0]
            print(j2)

            if len(j2) > 0:
                last = max(j2, key=np.abs)
            else:
                last = eigen_main_2

            frequency_last = 1000 * abs(float(last.imag) / (2 * 3.14159 * float(last.real)))
            net_freq.append([string_name, frequency_last])
            frequency_last_ = "%.2f" % frequency_last

            # Symmetric part
            lista_modulos_cuad = [i ** 2 for i in list_moduls]

            # Henrici’s departure from normality
            H_number = np.sqrt(np.power(np.linalg.norm(connection_used), 2)
                               - sum(lista_modulos_cuad)) / np.linalg.norm(connection_used)
            H_number_list.append([mem_gap, H_number])

            # Symmetric matrix analysis:
            w_s, v_s = LA.eig(connection_sym)

            lista_dist_s = np.c_[w_s, w_s.real]
            lista_dist_2_s = np.c_[w_s, abs(w_s.real)]
            maximum_s = max(lista_dist_s, key=lambda item: item[1])
            maximum_2_s = max(lista_dist_2_s, key=lambda item: item[1])
            marcar_s = maximum_s[0]
            marcar_2_s = maximum_2_s[0]

            # Eigenvalues Figure #
            fig = plt.figure(figsize=cm2inch(8.5, 8))
            plt.scatter(w.real, w.imag, color="k", label="Eigenvalue Spectrum",
                        s=2)  # Total of: "+str(len(w.real))+" values")
            plt.scatter(last.real, last.imag, color="blue",
                        label="Eigenvalue complex" + str(last) + "\nFreq: " + str(frequency_last_) + " Hz", s=5)
            # for plotting Circle line:
            a = np.linspace(0, 2 * np.pi, 500)
            cx, cy = np.cos(a), np.sin(a)
            plt.plot(cx, cy, '--', alpha=.5, color="dimgrey")  # draw unit circle line
            plt.scatter(eigen_main.real, eigen_main.imag, color="red",
                        label="Eigenvalue with max. real part \n" + str(eigen_main_2), s=5)
            plt.plot([0, eigen_main.real], [0, eigen_main.imag], '-', color="grey")
            plt.axvline(x=1, color="salmon", linestyle='--')
            plt.xticks(fontsize=10)
            plt.yticks(fontsize=10)
            plt.ylim([-1.4, 1.75])
            plt.xlim([-1.5, 1.65])
            plt.xlabel(r'$Re( \lambda)$', fontsize=11)
            plt.ylabel(r'$Im( \lambda)$', fontsize=11)
            leg = plt.legend(fontsize=5, loc=1)
            leg.get_frame().set_linewidth(0.0)
            plt.savefig(plot_dir + "/" + str(folder_name) + "autoval_" + str(i) + "_" + str(mem_gap)
                        + "_.png", dpi=300, bbox_inches='tight')
            plt.close(fig)

            # Plot Sym matrix Eigenvalues:

            fig = plt.figure(figsize=cm2inch(8.5, 8))
            plt.scatter(w_s.real, w_s.imag, color="k", label="Eigenvalue Sym spectrum\n" + str(marcar_2_s),
                        s=2)
            # for plotting circle line:
            a = np.linspace(0, 2 * np.pi, 500)
            cx, cy = np.cos(a), np.sin(a)
            plt.plot(cx, cy, '--', alpha=.5, color="dimgrey")
            plt.scatter(marcar_s.real, marcar_s.imag, color="red", label="Eigenvalue maximum real part", s=5)
            plt.plot([0, marcar_s.real], [0, marcar_s.imag], '-', color="grey")
            plt.axvline(x=1, color="salmon", linestyle='--')
            plt.xticks(fontsize=10)
            plt.yticks(fontsize=10)
            plt.ylim([-1.4, 1.75])
            plt.xlim([-1.5, 1.65])
            plt.xlabel(r'$Re( \lambda)$', fontsize=11)
            plt.ylabel(r'$Im( \lambda)$', fontsize=11)
            leg = plt.legend(fontsize=7, loc=1)
            leg.get_frame().set_linewidth(0.0)
            plt.savefig(plot_dir + "/" + str(folder_name) + "sym_auto" + str(i) + "_" + str(mem_gap) + "_.png",
                        dpi=300, bbox_inches='tight')
            plt.close(fig)

            # Model prediction for time series:
            x_pred = x_train[0:10, :, :]
            y_pred = model.predict(x_pred)

            distance_list = []

            # Figure for Connectivity matrix:
            fig2 = plt.figure(figsize=(15, 5))
            connection_show = np.ma.masked_where(abs(connection) < weight_mask, connection)
            ax = []
            # color bar setting:
            cbar_max = 1  # 0.75
            cbar_min = -1  # -0.75
            cbar_step = 0.025
            out = weights_out[0]

            # Colormap settings:
            # cmap = plt.get_cmap('Spectral')
            cmap = plt.get_cmap('seismic')
            # extract all colors from the .jet map
            cmaplist = [cmap(i) for i in range(cmap.N)]
            cmap = cmap.from_list('Custom cmap', cmaplist, cmap.N)
            cmap.set_bad(color='white')

            # define the bins and normalize and forcing 0 to be part of the colorbar!
            bounds = np.arange(np.min(connection_show), np.max(connection_show), .05)
            idx = np.searchsorted(bounds, 0)
            bounds = np.insert(bounds, idx, 0)
            norm_ = BoundaryNorm(bounds, cmap.N)
            # cmap = clr.LinearSegmentedColormap.from_list('custom blue',
            # ['#244162','#DCE6F1'], N=256)

            # W in (Input connectivity layer)
            ax.append(fig2.add_subplot(1, 3, 1))
            plt.title(r'$W^{in}$', fontsize=20)
            im1 = plt.imshow(weights_in.T, cmap=cmap,
                             interpolation="none", label=r'$W^{in}$', extent=[0, 1, 0, 100],
                             aspect='0.2', vmin=np.min(connection_show), vmax=np.max(connection_show))
            plt.xticks(np.arange(0, 2, 1))
            plt.yticks(np.arange(0, N_rec + 1, 5))

            # W rec (Recurrent layer)
            ax.append(fig2.add_subplot(1, 3, 2))
            plt.title(r'$W^{Rec}$', fontsize=20)

            im = plt.imshow(connection_show, interpolation='none', cmap=cmap, label='Connectivity matrix',
                            aspect="auto", vmin=np.min(connection_show), vmax=np.max(connection_show))
            plt.xlim([-1, N_rec + 1])
            plt.ylim([-1, N_rec + 1])
            plt.xticks(np.arange(0, N_rec + 1, 5))
            plt.yticks(np.arange(0, N_rec + 1, 5))
            plt.ylabel('Post-synaptic', fontsize=15)
            plt.xlabel('Pre-synaptic', fontsize=15)
            plt.colorbar(im, orientation='vertical')

            # W out (output layer)
            ax.append(fig2.add_subplot(1, 3, 3))
            plt.title(r'$W^{out}$', fontsize=20)
            im3 = plt.imshow(out, cmap=cmap, interpolation="none", label=r'$W^{out}$', extent=[0, 1, 0, 100],
                             aspect='0.2', vmin=np.min(connection_show), vmax=np.max(connection_show))
            # plt.colorbar(im3, orientation='vertical')
            plt.xticks(np.arange(0, 2, 1))
            plt.yticks(np.arange(0, N_rec + 1, 5))

            fig2.tight_layout()

            # plt.legend(fontsize='small', loc=1)
            plt.savefig(plot_dir + "/" + str(folder_name) + "_Connectivity_matrix_"
                        + str(i) + "_" + str(f) + "_.png", dpi=200)
            plt.close()

            # New code for weight distribution plots

            # Extract weights from each layer
            w_in = weights_in.flatten()  # Input layer (W_in)
            w_rec = connection_used.flatten()  # Recurrent layer (W_rec)
            w_out = weights_out[0].flatten()  # Output layer (W_out)

            # Create figure with three subpanels
            fig3 = plt.figure(figsize=(15, 6))

            # Extract weights from each layer and parameters
            w_in = weights_in.flatten()  # Input layer (W_in)
            w_rec = connection_used.flatten()  # Recurrent layer (W_rec)
            w_out = weights_out[0].flatten()  # Output layer (W_out)
            input_size = x_train.shape[2]  # Get input features dimension
            output_size = y_train.shape[2]  # Get output dimension


            def plot_weights(ax, weights, layer_name, N_rec, input_size=None, output_size=None):
                pos_weights = weights[weights > 0]
                neg_weights = weights[weights <= 0]
                bins = np.linspace(np.min(weights), np.max(weights), 50)
                bin_width = bins[1] - bins[0]

                # Plot histogram
                ax.hist(pos_weights, bins=bins, color='red', alpha=0.7, label='Positive')
                ax.hist(neg_weights, bins=bins, color='blue', alpha=0.7, label='Negative')

                # Plot theoretical initial distribution
                if layer_name == 'Input Layer' or layer_name == 'Output Layer':
                    # Glorot Uniform distribution
                    if layer_name == 'Input Layer':
                        fan_in = input_size
                        fan_out = N_rec
                    else:  # Output Layer
                        fan_in = N_rec
                        fan_out = output_size

                    limit = np.sqrt(6 / (fan_in + fan_out))
                    x = np.linspace(-limit, limit, 1000)
                    y = np.full_like(x, (1 / (2 * limit)) * len(weights) * bin_width)
                    ax.plot(x, y, '--', color='black', linewidth=2, label='Glorot Uniform Init')

                elif layer_name == 'Recurrent Layer':
                    # Initialization (approx normal)
                    stddev = 1 / np.sqrt(N_rec)
                    x = np.linspace(np.min(weights), np.max(weights), 1000)
                    y = norm.pdf(x, 0, stddev) * len(weights) * bin_width
                    ax.plot(x, y, '--', color='black', linewidth=2, label='Orthogonal Init')

                # Plot settings
                ax.set_title(f'{layer_name} Weight Distribution', fontsize=12)
                ax.set_xlabel('Weight Value', fontsize=10)
                ax.set_ylabel('Frequency', fontsize=10)
                ax.legend(fontsize=8)

                # Calculate proportions
                total = len(weights)
                pos_percent = len(pos_weights) / total * 100 if total != 0 else 0
                neg_percent = len(neg_weights) / total * 100 if total != 0 else 0
                majority = 'Positive' if pos_percent > neg_percent else 'Negative'

                # Annotation
                ax.text(0.05, 0.90,
                        f'Current Distribution:\nMajority: {majority}\nPos: {pos_percent: .1f}%\nNeg: {neg_percent: .1f}%',
                        transform=ax.transAxes,
                        verticalalignment='top',
                        fontsize=8,
                        bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))


            # Plot input layer
            ax1 = fig3.add_subplot(1, 3, 1)
            plot_weights(ax1, w_in, 'Input Layer', N_rec, input_size, output_size)

            # Plot recurrent layer
            ax2 = fig3.add_subplot(1, 3, 2)
            plot_weights(ax2, w_rec, 'Recurrent Layer', N_rec)

            # Plot output layer
            ax3 = fig3.add_subplot(1, 3, 3)
            plot_weights(ax3, w_out, 'Output Layer', N_rec, input_size, output_size)

            plt.tight_layout()
            plt.savefig(os.path.join(plot_dir, f"{folder_name}_WeightDistributionComparison_{i}_{f}.png"),
                        dpi=200, bbox_inches='tight')
            plt.close(fig3)

            # After existing eigenvalue plots:
            plot_schur_decomposition(connection_used, plot_dir, f"network_{i}")
            plot_sym_antisym_spectra(connection_used, plot_dir, f"network_{i}")
            plot_schur_decomposition(connection_used, plot_dir, f"network_{i}")

            # Figures for time series processing (h_i(t), activity)

            for sample_number in np.arange(sample_size_3):
                print_sample = plot_sample(sample_number, neurons, x_train, y_train,
                                           model, seq_dur, i, plot_dir, f, string_name, mem_gap)
                list_freq_sample_net.append(print_sample)

            # Distance estimation:
            for ii in np.arange(0, 10, 1):
                a = y_train[ii, :, 0]
                b = y_pred[ii, :, 0]
                a_min_b = np.linalg.norm(a - b)
                distance_list.append(a_min_b)
            distance_list.insert(0, mem_gap)
            distance_list_all.append(distance_list)
            #########################################

            fig = plt.figure(figsize=cm2inch(10, 8.5))
            for ii in np.arange(6):
                ab = "%.4f" % a_min_b
                a = y_train[ii, :, 0]
                b = y_pred[ii, :, 0]
                a_min_b = np.linalg.norm(a - b)
                plt.subplot(3, 2, ii + 1)
                plt.plot(x_train[ii + 3, :, 0], color='g', label="Input")
                if x_train.shape[2] == 2:
                    plt.plot(x_train[ii + 3, :, 1], color='pink', label="Cue")
                plt.plot(y_train[ii + 3, :, 0], color='gray', linewidth=2, label="Expected Output")
                plt.plot(y_pred[ii + 3, :, 0], color='r', linewidth=1,
                         label="Predicted Output\n Distance " + str(ab))
                plt.ylim([-2.5, 2.5])
                plt.xticks(np.arange(0, len(y_train[ii + 3]) + 5, 50), fontsize=8)
                leg = plt.legend(fontsize=3.5, loc=3)
                leg.get_frame().set_linewidth(0.0)
                plt.yticks([])
                plt.xticks(fontsize=4)
                plt.yticks(fontsize=4)
            fig.text(0.5, 0.03, 'time [ms]', fontsize=5, ha='center')
            fig.text(0.1, 0.5, 'Amplitude [Arb. Units]', va='center', ha='center',
                     rotation='vertical', fontsize=5)
            figname = plot_dir + "/" + str(folder_name) + "_data_set_" \
                      + str(weight_mask) + '_' + str(mem_gap) + "_.png"
            plt.savefig(figname, dpi=300, bbox_inches='tight')
            plt.close(fig)

            all_data_2 = np.c_[distance_list_all]

            np.savetxt(plot_dir + "/" + str(folder_name) + '_distance_sample.txt', all_data_2,
                       fmt='%f %f %f %f %f %f %f %f %f %f %f', delimiter=' ',
                       header="time_delay #S1 #S2 #S3 #S4 #S5 #S6 #S7 #S8 #S9 #S10")
            np.savetxt(plot_dir + "/" + str(folder_name) + '_freq_net.txt', net_freq, fmt='%s %s',
                       delimiter='\t', header="Name #freq ")
            np.savetxt(plot_dir + "/" + str(folder_name) + '_freq_net_units.txt', list_freq_sample_net,
                       fmt='%s', delimiter='\t', header="Name #sample #freq")
            np.savetxt(plot_dir + "/" + str(folder_name) + '_H_number.txt', H_number_list, fmt='%s %s',
                       delimiter='\t', header="time_delay #H number")

            print("Distances", all_data_2)
            print("Freq estimated from Networks", net_freq)
            print("Freq. estimated from units", list_freq_sample_net)
